---
title: "test"
format: 
        html:
                code-fold: true
                code-overflow: scroll
                code-summary: 'Show the code'
                self-contained: true
                toc: true
                fig-align: center
                theme: cerulean
                message: false
editor: source
params:
        username: 'phenrickson'
---

## View Collections


```{r}
options(knitr.duplicate.label = "allow")
```


```{r}
#| echo: false
#| include: false
library(targets)
library(dplyr)
library(tibble)
library(gt)
library(gtExtras)
library(ggrepel)
library(tibble)
library(dplyr)
library(rsample)
library(tidymodels)
library(bggUtils)

```


```{r}

tar_source("src/data/load_data.R")
tar_source("src/models/splitting.R")
tar_source("src/models/training.R")
tar_source("src/visualization/inference.R")
tar_source("src/visualization/tables.R")
tar_source("src/visualization/plots.R")

```

```{r}
#| include: false
tar_load(games_raw)
tar_load(games)
username = params$username

tar_load(paste("collection", username, sep = "_"))
tar_load(paste("model_glmnet", username, sep = "_"))

collection = 
        get(ls(pattern = paste("collection", username, sep = "_")))

model = 
        get(ls(pattern = paste("model_glmnet", username, sep = "_")))

```

```{r}
#| fig-height: 7
collection |>
        filter(own == 1) |>
        collection_by_category(
                games = games_raw
        ) |>
        plot_collection_by_category()

```

```{r}

collection |>
        filter(own == 1) |>
        prep_collection_datatable(
                games = games_raw
        ) |>
        collection_datatable()
```


```{r}

top_coefs_plot = 
        model |> 
        pluck("wflow", 1) |>
        get_coefs.glmnet() |>
        top_coefs_by_sign() |>
        coef_plot.glmnet()

```

```{r}
#| fig-height: 6
top_coefs_plot

```

```{r}
#| warning: false
#| message: false
model |> 
        pluck("wflow", 1) |>
        trace_plot.glmnet(max.overlaps = 30)

```
